
# Investment Submissions Webhook Function
# This webhook handles new investment submissions and integrates with Zapier

# To deploy this function, run:
# supabase functions deploy investment-submissions-webhook
